solo/ideas/urls.py
from django.urls import path
from ideas import views

app_name = 'ideas'

urlpatterns = [
  path('register', views.register, name='register'),
  path('user_login', views.user_login, name='user_login'),
  path('post', views.post, name='post'),
  path('create_post', views.create_post, name='create_post'),
  path('<user_id>/member_details', views.member_details, name='member_details'),
  path('<post_id>/delete_post', views.delete_post, name='delete_post'),
  path('<post_id>/', views.who_likes, name='who_likes'),
  path('<post_id>/likers', views.likers, name='likers'),
  path('<post_id>/edit_post', views.edit_post, name='edit_post'),
  path('<post_id>/edit', views.edit, name='edit'),
  path('<post_id>/add_comment', views.add_comment, name='add_comment'),
  path('profile', views.profile, name='profile'),
  path('user_posts', views.user_posts, name='user_posts'),
  path('<int:comment_id>/delete_comment', views.delete_comment, name='delete_comment'),
  path('search', views.search, name='search'),
]

solo/solo/urls.py
from django.contrib import admin
from django.urls import path, include
from ideas import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('ideas/', include('ideas.urls')),
    path('user_logout/', views.user_logout, name='user_logout'),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

solo/ideas/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  portfolio_site = models.URLField(blank=True)
  profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

  def __str__(self):
    return self.user.username
class PostManager(models.Manager):
  def validate_post(self, postFormData):
    error = {}
    if len(postFormData['title']) < 3:
      error['title'] = 'Title should be at least 3 charactors'
    if len(postFormData['editor1']) < 3:
      error['editor1'] = 'Post content should be at least 5 charactors'
    
    return error


class Post(models.Model):
  title = models.CharField(max_length=255)
  content = models.TextField()
  author = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
  who_likes = models.ManyToManyField(User, related_name='liked_posts')
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  objects = PostManager()

class Comment(models.Model):
  comment_content = models.CharField(max_length=255)
  user = models.ForeignKey(User, related_name='user_comments', on_delete=models.CASCADE)
  post = models.ForeignKey(Post, related_name='post_comment', on_delete=models.CASCADE)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

solo/ideas/forms.py
from django import forms
from django.contrib.auth.models import User
from ideas.models import UserProfileInfo, Post
from django.core import validators

def check_email(value):
  if len(value) < 3:
    raise forms.ValidationError('Title must be at least 3 characters')

class UserForm(forms.ModelForm):
  password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
  email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
  username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
  
  class Meta():
    model = User
    fields = ('username', 'email', 'password')

    widgets = {
      'username': forms.TextInput(attrs={'class': 'form-control'}),
      'email': forms.EmailInput(attrs={'class': 'form-control'})
    }
   
class UserProfileInfoForm(forms.ModelForm):
  class Meta():
    model = UserProfileInfo
    fields = ('portfolio_site', 'profile_pic')

    widgets = {
      'portfolio_site': forms.URLInput(attrs={'class': 'form-control'}),
      'profile_pic': forms.FileInput(attrs={'class': 'btn btn-outline-dark'})
    }

solo/ideas/views.py
from django.shortcuts import render, redirect, HttpResponse
from ideas.forms import UserForm, UserProfileInfoForm
from ideas.models import User, Post, UserProfileInfo, Comment
from django.core.paginator import Paginator
import datetime
from django.utils import timezone

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

from django.db.models import Count
from ideas.models import PostManager
from django.contrib import messages

# Create your views here.
def index(request):
  users = User.objects.all()
  all_posts = Post.objects.all()
  posts = most_liked = Post.objects.annotate(like_count=Count('who_likes')).order_by('-like_count')

  paginator = Paginator(posts, 2)
  page = request.GET.get('page')
  posts = paginator.get_page(page)

  context = {
    'posts': posts,
    'users': users,
    'all_posts': all_posts
  }
  return render(request, 'ideas/index.html', context)


@login_required(login_url='/ideas/user_login')
def delete_comment(request, comment_id):
  comment_to_delete = Comment.objects.get(id=comment_id)
  if comment_to_delete.user.id == request.user.id:
    comment_to_delete.delete()
    return redirect('index')
  else:
    return redirect('index')


@login_required(login_url='/ideas/user_login')
def post(request):
  return render(request, 'ideas/post.html')

@login_required(login_url='/ideas/user_login')
def profile(request):
  return render(request, 'ideas/profile.html', {'user': request.user})

@login_required
def user_logout(request):
  logout(request)
  return redirect('index')

def register(request):
  registered = False
  if request.method == 'POST':
    user_form = UserForm(data=request.POST)
    profile_form = UserProfileInfoForm(data=request.POST)

    if user_form.is_valid() and profile_form.is_valid():
      user = user_form.save()
      user.set_password(user.password)
      user.save()

      profile = profile_form.save(commit=False)
      profile.user = user

      if 'profile_pic' in request.FILES:
        profile.profile_pic = request.FILES['profile_pic']
        profile.save()
      
      registered = True
    else:
      print('something went wrong')
  else:
    user_form = UserForm()
    profile_form = UserProfileInfoForm()
    
  return render(request, 'ideas/register.html', {
    'registered': registered,
    'user_form': user_form,
    'profile_form': profile_form
  })

def user_login(request):
  if request.method == 'POST':
    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(username=username, password=password)

    if user:
      if user.is_active:
        login(request, user)
        return redirect('index')
      else:
        return HttpResponse('You are not signed in')
    else:
      return HttpResponse('<h1 style="color:red; background:yellow;">Username or Password is wrong! Please check your login information</h1>')
  else:
    return render(request, 'ideas/login.html',{})

@login_required(login_url='/ideas/user_login')
def create_post(request):
  errors = Post.objects.validate_post(request.POST)
  
  if errors:
    for values in errors.values():
      messages.error(request, values)
    return redirect('/ideas/post')
  else:
      new_post = Post.objects.create(title=request.POST['title'], content=request.POST['editor1'],  author=request.user)
      return redirect('index')

@login_required(login_url='/ideas/user_login')
def delete_post(request, post_id):
  post_to_delete = Post.objects.get(id=post_id)
  post_to_delete.delete()
  return redirect('index')

@login_required(login_url='/ideas/user_login')
def member_details (request, user_id):
  context = {
    'one_user': User.objects.get(id=user_id)
  }
  return render(request, 'ideas/user.html', context)

@login_required(login_url='/ideas/user_login')
def who_likes(request, post_id):
  post_to_like = Post.objects.get(id=post_id)
  request.user.liked_posts.add(post_to_like)
  return redirect('index')

@login_required(login_url=('/ideas/user_login'))
def likers(request, post_id):
  context = {
    'liked_post': Post.objects.get(id=post_id),
    'portfolios': UserProfileInfo.objects.all()
  }
  return render(request, 'ideas/post_likers.html', context)

@login_required(login_url='/ideas/user_login')
def user_posts(request):
  context = {
    'current_user_posts': Post.objects.filter(author=request.user)
  }
  return render(request, 'ideas/user_posts.html', context)

@login_required(login_url=('/ideas/user_login'))
def edit_post(request, post_id):
  current_post = Post.objects.get(id=post_id)
  return render(request, 'ideas/edit_post.html', {'current_post': current_post})

@login_required(login_url='/ideas/user_login')
def edit(request, post_id):
  post_to_edit = Post.objects.get(id=post_id)
  post_to_edit.title = request.POST['title']
  post_to_edit.content = request.POST['editor1']
  post_to_edit.save()
  return redirect('index')

@login_required(login_url=('/ideas/user_login'))
def add_comment(request, post_id):
    post_to_comment = Post.objects.get(id=post_id)
    Comment.objects.create(
    comment_content=request.POST['comment'],
    post = post_to_comment,
    user = request.user
    )
    return redirect('index')

def search(request):
  now = timezone.now()
  qs = Post.objects.all()
  title_contains = request.GET.get('title_contains')

  if title_contains != '' and title_contains is not None:
    qs = qs.filter(title__icontains=title_contains)

  context = {
      'queryset': qs
    }
  return render(request, 'ideas/search.html', context)

solo/templates/ideas/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Bright Ideas</title>
  <script src="https://kit.fontawesome.com/3953f86343.js" crossorigin="anonymous"></script>
  
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">

  <script defer src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

  <script defer src="{% static 'ideas/app.js' %}"></script>
 <link rel="stylesheet" href="{% static 'ideas/style.css' %}">
</head>
<body class="bg-light">
  <div class="image-overlay">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark py-2">
    <div class="container">
      <a href="{% url 'index'%}" class="navbar-brand"><img src="/static/ideas/images/lightbulb.jpg"  alt="" class="brand "> Bright Ideas</a>

      <form action="{% url 'ideas:search' %}" method="GET" class="input-group search_form">
        <input type="search" name="title_contains" class="form-control form-control-sm" placeholder="Search Ideas...">
        <div class="input-group-append">
          <button class="btn bg-light text-dark btn-sm"><i class="fas fa-search"></i></button>
        </div>
      </form>

      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav">
        </ul>

        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item dropdown mr-3">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
              <i class="fas fa-user"></i> Welcome {{user.username}}
            </a>
            <div class="dropdown-menu">
              <a href="{% url 'ideas:profile'%}" class="dropdown-item">
                <i class="fas fa-user-circle"></i> Profile
              </a>
              <a href="{% url 'ideas:user_posts' %}" class="dropdown-item"><i class="fas fa-folder"></i> Posts
              </a>
              
            </div>
          </li>
          {% else %}
          <li class="nav-item dropdown mr-3">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
              <i class="fas fa-user"></i> Welcome, Guest
            </a>
            <div class="dropdown-menu">
              <a href="{% url 'ideas:register' %}" class="dropdown-item">
                <i class="fas fa-hand-point-right"></i> Sign Up
              </a>
              <a href="{% url 'index' %}" class="dropdown-item">
                <i class="fas fa-cog"></i> Continue as Guest
              </a>
            </div>
          </li>
          {% endif %}



          {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'user_logout'%}" class="nav-link">
              <i class="fas fa-user-times"></i> Logout
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a href="{% url 'ideas:user_login'%}" class="nav-link">
              <i class="fas fa-user"></i> Login
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

    {% block body_block %}
 
    {% endblock %}
  



  <!-- external liberires -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>



<script src="https://cdn.ckeditor.com/4.9.2/standard/ckeditor.js"></script>

<script>
  CKEDITOR.replace('editor1');
</script>

<footer class="footer bg-dark text-center text-white py-3 fixed-bottom border-top">
  <span>Bright Ideas 2020</span>
</footer>
  </div>
</body>
</html>

solo/templates/ideas/edit_post.html
{% extends 'ideas/base.html' %}
{% block body_block %}
  <div class="container mt-3">
    <div class="jumbotron">
      <h3 class="text-center mb-4">Edit Your Post</h3>
      <form action="{% url 'ideas:edit' current_post.id %}" method="post" class="form-group">
        {% csrf_token %}
        <label for="title">Title</label>
        <input type="text" name="title" id="title" value="{{current_post.title}}" class="form-control">
        <label for="text_areda">Content</label>
        <textarea name="editor1" id="text_area" class="form-control">{{current_post.content|safe}}</textarea>
        <input type="submit" value="Edit Post" class="btn btn-outline-dark mt-3">
      </form>
    </div>

  </div>
{% endblock %}

solo/templates/ideas/index.html
{% extends 'ideas/base.html' %}
{% load tz %}
{% block body_block %}

<section id="posts">

  <!-- Modal -->

  <div class="container mt-4 mb-5">

    <div class="row">
      <div class="col-md-9">
        {% for post in posts %}
        <div class="card mb-2">
          <div class="card-body">
            <h4>{{post.title}}</h4>
            <p class="lead">{{post.content | safe}}</p>
            <p class="figure-caption">Posted by: <a
                href="{% url 'ideas:member_details' post.author.id %}">{{post.author.username}}</a> On:
              {{post.created_at | date }}</p>

            <div class="people_like mt-2 mb-4 d-flex justify-content-between">
              <span class="text-muted"> <i class="far fa-thumbs-up"></i>
                <a href="{% url 'ideas:likers' post.id %}" class="likers">
                  {{post.who_likes.count}} users(s)</a> like this idea!</span>
              <div><a data-toggle="collapse" href="#collapse{{post.id}}" role="button" aria-expanded="false"
                  aria-controls="collapseComments">{{post.post_comment.count}} Comments</a></div>
            </div>

            <!-- comment form accordian -->
            <div class="collapse container" id="collapseComments{{post.id}}">
              <form action="{% url 'ideas:add_comment' post.id %}" post_id='{{post.id}}' method="post"
                class="form-group" id="comment">
                {% csrf_token%}
                <input type="text" name="comment" class="form-control rounded-pill border border-dark"
                  placeholder="Write a comment...">
              </form>
            </div>

            <!-- comments content -->

            {% for comment in post.post_comment.all %}
            <div class="my-2 bg-light collapse p-2 font-italic border rounded-sm comments" id="collapse{{post.id}}">
              <a href="{% url 'ideas:member_details' comment.user.id %}">
                {% if comment.user.userprofileinfo.profile_pic %}
                <img src="{{ comment.user.userprofileinfo.profile_pic.url}}" alt="profile picture"
                  class="img-fluid rounded-circle" width="50">
                {% else %}
                <img src="/media/default.jpg" alt="avator profile" class=" img-fluid rounded-circle" width="50">
                {% endif %}
              </a>
              {% if comment.user.id == request.user.id %}
              <span class="ml-2 mt-auto bg-light">{{comment.comment_content}} <a
                  href="{% url 'ideas:delete_comment' comment.id %}"><span class="figure-caption text-danger">Delete!</span></a></span>
              {% else %}
              <span class="ml-2 mt-auto bg-light">{{comment.comment_content}}</span>
              {% endif %}
            </div>
            {% endfor %}


            <div class="like_comment mt-3 d-flex justify-content-around border">
              <a href="{% url 'ideas:who_likes' post.id %}" class="btn text-dark"><i class="fas fa-thumbs-up fa-1x"></i>
                Like</a>
              <!-- comment accordian btn -->
              <a class="btn text-dark" data-toggle="collapse" href="#collapseComments{{post.id}}" role="button"
                aria-expanded="false" aria-controls="collapseExample"><i class="far fa-comment-alt"></i> Comment</a>

              <a class="btn text-dark" data-toggle="collapse" href="#collapseShare{{post.id}}" role="button"
                aria-expanded="false" aria-controls="collapseShare"><i class="fas fa-share"></i> Share</a>

            </div>

            {% if request.user.id == post.author.id %}
            <div class="action mt-3">

              <!-- Delete Button trigger modal -->
              <a href="{% url 'ideas:delete_post' post.id %}" class="btn btn-outline-danger btn-sm">Delete Post</a>


              <!-- edit post -->
              <a href="{% url 'ideas:edit_post' post.id %}" class="btn btn-outline-primary ml-2 btn-sm">Edit Post</a>
            </div>
            {% endif %}
          </div>
          <!-- share message -->
          <div class="collapse container my-2" id="collapseShare{{post.id}}">
            <div class="aler alert-info rounded p-3" role="alert">
              This feature is Coming Soon!!
            </div>
          </div>

        </div>
        {% endfor %}
        <!-- pagination -->
        <nav aria-label="Page navigation">
          <ul class="pagination mb-3">
            {% if posts.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">
                <<</a> </li> <li class="page-item"><a class="page-link" href="?page={{posts.previous_page_number}}">
                    <</a> </li> {% endif %} {% for num in posts.paginator.page_range %} {% if posts.number == num %} <li
                      class="page-item mx-1"><a class="page-link bg-dark text-white" href="{{posts.number}}">{{num}}</a>
            </li>
            {% else %}
            <li class="page-item mx-1"><a class="page-link" href="?page={{num}}">{{num}}</a></li>
            {%endif%}
            {% endfor %}
            {% if posts.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{posts.next_page_number}}">></a></li>
            <li class="page-item"><a class="page-link" href="?page={{posts.paginator.num_pages}}">>></a></li>
            {% endif %}
          </ul>
        </nav>

      </div>

      <div class="col-md-3">
        <div class="card text-center bg-dark text-white mb-3">
          <div class="card-body">
            <h3>Share Your Ideas!</h3>
            <h4 class="display-4">
              <i class="fas fa-bullhorn"></i>
            </h4>
            <a href="{% url 'ideas:post'%}" class="btn btn-outline-light btn-sm">Post An Idea!</a>
          </div>
        </div>

        <div class="card text-center bg-primary text-white mb-3">
          <div class="card-body">
            <h3><span>{{users.count}}</span> Members!</h3>
            <h4 class="display-4">
              <i class="fas fa-users"></i>
            </h4>
            <a href="{% url 'ideas:register'%}" class="btn btn-outline-light btn-sm">Join The Ninjas!</a>
          </div>
        </div>

        <div class="card text-center bg-dark text-white mb-3">
          <div class="card-body">
            <h3>All Shared Ideas.</h3>
            <h4 class="display-4">
              <i class="far fa-lightbulb"></i>
            </h4>
            <h3> {{all_posts.count}} Creative Ideas!</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

solo/templates/ideas/login.html
{% extends 'ideas/base.html' %}

{% block body_block %}
<div class="half_width">
  <div class="container mt-5">
    <div class="jumbotron">
      <h3 class="text-center mb-3"><i class="fas fa-user-circle"></i> Login</h3>
      <form action="{% url 'ideas:user_login' %}" method="POST" class="form-group">
        {% csrf_token %}
        <label for="user">Username</label>
        <input type="text" name="username" id="user" class="form-control">
        <label for="password">Password</label>
        <input type="password" name="password" id="password" class="form-control">
        <input type="submit" value="Sig In" class="btn btn-outline-dark mt-3">
      </form>
      <p class="lead mt-5 mb-0">Don't have an account with us, <a href="{% url 'ideas:register'%}"><i class="fas fa-chevron-circle-right"></i> Register Here</a></p>
    </div>
  </div>
</div>
{% endblock %}

solo/templates/ideas/post.html
{% extends 'ideas/base.html' %}

{% block body_block %}
<div class="container">
    <div class="jumbotron">

      {% for message in messages %}
      <div class="alert alert-warning mb-3" role="alert">{{message}}</div>
      {% endfor %}
      <h3>Create a Post!</h3>
      <form action="{% url 'ideas:create_post'%}" method="post" class="form-group" id="post">
        {% csrf_token %}
        <label for="title">Title</label>
        <input type="text" name="title" id="title" class="form-control">
        <label for="text_areda">Content</label>
        <textarea name="editor1" id="" class="form-control"></textarea>
        <input type="submit" value="Post Your Idea!" class="btn btn-dark mt-3">
      </form>
    </div>
  </div>
{% endblock %}

solo/templates/ideas/post_likers.html
{% extends 'ideas/base.html' %}
{% block body_block %}


<div class="half_width">
  <div class="container mt-3">
    <div class="jumbotron">
      <u>
        <h3 class="mb-5 font-italic">Users who like this idea!</h3>
      </u>
      <ul class="list-group">
        {% for user in liked_post.who_likes.all %}

        {% if user.userprofileinfo.profile_pic %}
        <li class="d-flex list-group-item">
          <img src="{{ user.userprofileinfo.profile_pic.url}}" alt="" class="d-block img-fluid rounded-circle mr-3"
            width="50"> <a href="{% url 'ideas:member_details' user.id%}"
            class="align-self-center">{{user.username}}</a>
        </li>
        {% else %}
        <li class="d-flex list-group-item">
          <img src="/media/default.jpg" alt="" class="d-block img-fluid rounded-circle mr-3" width="50">
          <a href="{% url 'ideas:member_details' user.id%}" class="align-self-center">{{user.username}}</a>
        </li>
        {% endif %}

        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

solo/templates/ideas/profile.html
{% extends 'ideas/base.html'%}

{% block body_block %}
<div class="half_width">
<div class="container">
  <div class="jumbotron m-auto">
    <div class="row">
      <div class="col-md-3">
      <h6>User Image</h6>
      {% if user.userprofileinfo.profile_pic %}
      <img src="{{ user.userprofileinfo.profile_pic.url}}" alt="" class="d-block img-fluid mb-3">
      {% else %}
      <img src="/media/default.jpg" alt="" class="d-block img-fluid mb-3">
      {% endif %}
      </div>
      <div class="col-md-9">
        <h6>User Profile</h6>
        <ul class="list-group">
          <li class="list-group-item">Username: {{user.username}}</li>
          <li class="list-group-item">Email: {{user.email}}</li>

          {% if user.userprofileinfo.portfolio_site%}
          <li class="list-group-item">Portfolio site: <a href="{{user.userprofileinfo.portfolio_site}}">{{user.userprofileinfo.portfolio_site}}</a></li>
          {% else %}
          <li class="list-group-item">Email me at: <a href="mailto:{{user.email}}">{{user.email}}</a></li>
          {% endif%}
        </ul>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

solo/templates/ideas/register.html
{% extends 'ideas/base.html'%}

{% block body_block %}
<div class="half_width">
  <div class="container mt-2">
    <div class="jumbotron">
      {% if registered %}
      <h1>Thank you for registering and welcome to the innovators group.</h1>
      {% else %}
      <h3 class="mb-4 text-center"><i class="fas fa-user-plus"></i> Registeration</h3>
      <form enctype="multipart/form-data" method="POST" class="form-group">
        {% csrf_token %}
        {{user_form.as_p}}
        {{profile_form.as_p}}
        <input type="submit" value="Register" class="btn btn-outline-dark">
      </form>
    {% endif %}
    <p class="lead">Already registered <a href="{% url 'ideas:user_login'%}"><i class="fas fa-sign-in-alt"></i> Login</a></p>
    </div>
  </div>
</div>
{% endblock %}

solo/templates/ideas/search.html
{% extends 'ideas/base.html' %}
{% block body_block %}
 <div class="container mt-5">

  <h4 class="text-center text-info mb-3 font-italic figure-caption">Found {{queryset.count}} Idea(s) that matched your search!</h4>


  <div class="accordion" id="postModal">
    {% for post in queryset %}

      <div class="card">
        <div class="card-header" id="headingOne">
          <h2 class="mb-0">
            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse{{post.id}}" aria-expanded="true" aria-controls="collapseOne"><i class="fas fa-hand-point-down"></i> {{post.title}}</button>
          </h2>
        </div>
    
        <div id="collapse{{post.id}}" class="collapse hide" aria-labelledby="headingOne" data-parent="#postModal">
          <div class="card-body">
            <p class="lead">{{post.content | safe }}</p>
            <p class="text-muted">Posted by: <a href="{% url 'ideas:member_details' post.author.id %}">{{post.author.username}}</a> on {{post.created_at}}</p>
          </div>
        </div>
      </div>

    {% endfor %}
    
 </div>
{% endblock %}

solo/templates/ideas/user_posts.html
{% extends 'ideas/base.html'%}
{% block body_block %}
  <div class="container">
    <h3 class="text-center my-3">These are all the ideas you posted here</h3>
    {% for post in current_user_posts %}

    <div class="card">
      <div class="card-body mb-5">
        <h3>{{post.title}}</h3>
        <p class="lead">{{post.content | safe}}</p>
        <p class="text_muted">Posted by: <a href="{% url 'ideas:member_details' post.author.id %}">{{post.author.username}}</a> on {{post.created_at}}</p>
        {% if request.user.id == post.author.id %}
        <div class="action mt-3">

          <!-- Delete Button trigger modal -->
          <a href="{% url 'ideas:delete_post' post.id %}" class="btn btn-outline-danger btn-sm" >Delete Post</a>


          <!-- edit post -->
          <a href="{% url 'ideas:edit_post' post.id %}" class="btn btn-outline-primary ml-2 btn-sm">Edit Post</a>
        </div>
        {% endif %}
      </div>
    </div>

    {% endfor %}
  </div>
{% endblock %}